DROP TRIGGER TRG_AEVENT_LOG
/


DROP TRIGGER TRG_ASESSION
/


DROP TRIGGER TRG_AUSER
/



CREATE TRIGGER TRG_AEVENT_LOG
BEFORE INSERT ON AEVENT_LOG
    FOR EACH ROW
    BEGIN
    IF :NEW.AEVENT_LOG_ID IS NULL THEN
        SELECT SEQ_AEVENT_LOG.NEXTVAL INTO :NEW.AEVENT_LOG_ID FROM DUAL;
    END IF;
END;
/


CREATE TRIGGER TRG_ASESSION
BEFORE INSERT ON ASESSION
    FOR EACH ROW
    BEGIN
    IF :NEW.ASESSION_ID IS NULL THEN
        SELECT SEQ_ASESSION.NEXTVAL INTO :NEW.ASESSION_ID FROM DUAL;
    END IF;
END;
/


CREATE TRIGGER TRG_AUSER
BEFORE INSERT ON AUSER
    FOR EACH ROW
    BEGIN
    IF :NEW.AUSER_ID IS NULL THEN
        SELECT SEQ_AUSER.NEXTVAL INTO :NEW.AUSER_ID FROM DUAL;
    END IF;
END;
/

